version: '3.7'

services:
  neverquest-game-server:
    image: neverquest-game-server:latest
    ports:
      - "5001:5001"
    container_name: game-server

  neverquest-account-server:
    image: neverquest-account-server:latest
    ports:
      - "8082:8082"
    container_name: account-server
    volumes:
      - type: bind
        source: ../persistence/neverquest.db 
        target: /home/neverquest/persistence/neverquest.db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: redis

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - advertised.listeners=PLAINTEXT://localhost:9092
    container_name: kafka
  
  zookeeper:
    image: zookeeper:latest
    ports: 
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    container_name: zookeeper