name: Neverquest Docker Action

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: neverquest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and Push Docker Images
      env:
        ECR_GAME_SERVER_REPOSITORY: ${{ secrets.ECR_GAME_SERVER_REPOSITORY }}
        ECR_ACCOUNT_SERVER_REPOSITORY: ${{ secrets.ECR_ACCOUNT_SERVER_REPOSITORY }}
        IMAGE_TAG: latest
      run: |
        docker build -f docker/game-server/Dockerfile -t $ECR_GAME_SERVER_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_GAME_SERVER_REPOSITORY:$IMAGE_TAG
        docker build -f docker/account-server/Dockerfile -t $ECR_ACCOUNT_SERVER_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_ACCOUNT_SERVER_REPOSITORY:$IMAGE_TAG

